/**
 * A deliberately bounded, first-party-heavy source list for the free pilot.
 *
 * Feed and article hosts are exact allowlists. A source may redirect only to a
 * host named here; adding a source is therefore a reviewed code change rather
 * than something source-controlled XML can do at runtime.
 */
export const FREE_FEED_SOURCES = Object.freeze([
  {
    id: "openai-news",
    publisher: "OpenAI",
    publisherKey: "openai",
    primaryEntity: "OpenAI",
    relationship: "originating",
    format: "xml",
    url: "https://openai.com/news/rss.xml",
    feedHosts: ["openai.com", "www.openai.com"],
    itemHosts: ["openai.com", "www.openai.com"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 28, "work-and-tools": 5 },
  },
  {
    id: "google-ai",
    publisher: "Google",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://blog.google/technology/ai/rss/",
    feedHosts: ["blog.google"],
    itemHosts: ["blog.google"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 26, "work-and-tools": 4, "platforms-and-power": 3 },
  },
  {
    id: "google-research",
    publisher: "Google Research",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://research.google/blog/rss/",
    feedHosts: ["research.google"],
    itemHosts: ["research.google"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 22 },
  },
  {
    id: "apple-machine-learning",
    publisher: "Apple Machine Learning Research",
    publisherKey: "apple",
    primaryEntity: "Apple",
    relationship: "originating",
    format: "xml",
    url: "https://machinelearning.apple.com/rss.xml",
    feedHosts: ["machinelearning.apple.com"],
    itemHosts: ["machinelearning.apple.com"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 25 },
  },
  {
    id: "nvidia-deep-learning",
    publisher: "NVIDIA",
    publisherKey: "nvidia",
    primaryEntity: "NVIDIA",
    relationship: "originating",
    format: "xml",
    url: "https://blogs.nvidia.com/blog/category/enterprise/deep-learning/feed/",
    feedHosts: ["blogs.nvidia.com"],
    itemHosts: ["blogs.nvidia.com"],
    coverageDesks: ["ai", "platforms-and-power"],
    deskPriors: { ai: 23, "platforms-and-power": 6 },
  },
  {
    id: "microsoft-research",
    publisher: "Microsoft Research",
    publisherKey: "microsoft",
    primaryEntity: "Microsoft",
    relationship: "originating",
    format: "xml",
    url: "https://www.microsoft.com/en-us/research/feed/",
    feedHosts: ["www.microsoft.com"],
    itemHosts: ["www.microsoft.com"],
    coverageDesks: ["ai", "work-and-tools"],
    deskPriors: { ai: 16, "work-and-tools": 8 },
  },
  {
    id: "hugging-face-blog",
    publisher: "Hugging Face",
    publisherKey: "hugging-face",
    primaryEntity: "Hugging Face",
    relationship: "originating",
    format: "xml",
    url: "https://huggingface.co/blog/feed.xml",
    feedHosts: ["huggingface.co"],
    itemHosts: ["huggingface.co"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 25, "work-and-tools": 3 },
  },
  {
    id: "github-changelog",
    publisher: "GitHub",
    publisherKey: "microsoft",
    primaryEntity: "GitHub",
    relationship: "originating",
    format: "xml",
    url: "https://github.blog/changelog/feed/",
    feedHosts: ["github.blog"],
    itemHosts: ["github.blog"],
    coverageDesks: ["work-and-tools"],
    deskPriors: { "work-and-tools": 24, "security-and-privacy": 4 },
  },
  {
    id: "google-workspace-updates",
    publisher: "Google Workspace Updates",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://feeds.feedburner.com/GoogleAppsUpdates",
    feedHosts: ["feeds.feedburner.com"],
    itemHosts: ["workspaceupdates.googleblog.com"],
    coverageDesks: ["work-and-tools"],
    deskPriors: { "work-and-tools": 26 },
  },
  {
    id: "gitlab-blog",
    publisher: "GitLab",
    publisherKey: "gitlab",
    primaryEntity: "GitLab",
    relationship: "originating",
    format: "xml",
    url: "https://about.gitlab.com/atom.xml",
    feedHosts: ["about.gitlab.com"],
    itemHosts: ["about.gitlab.com"],
    coverageDesks: ["work-and-tools", "security-and-privacy"],
    deskPriors: { "work-and-tools": 23, "security-and-privacy": 4 },
  },
  {
    id: "mozilla-hacks",
    publisher: "Mozilla Hacks",
    publisherKey: "mozilla",
    primaryEntity: "Mozilla",
    relationship: "originating",
    format: "xml",
    url: "https://hacks.mozilla.org/feed/",
    feedHosts: ["hacks.mozilla.org"],
    itemHosts: ["hacks.mozilla.org"],
    coverageDesks: ["work-and-tools"],
    deskPriors: { "work-and-tools": 15, "security-and-privacy": 5 },
  },
  {
    id: "cisa-advisories",
    publisher: "CISA",
    publisherKey: "cisa",
    primaryEntity: "CISA",
    relationship: "originating",
    format: "xml",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    feedHosts: ["www.cisa.gov"],
    itemHosts: ["www.cisa.gov"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 30 },
  },
  {
    id: "google-security",
    publisher: "Google Security Blog",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    // The vanity Blogger endpoint currently redirects through an HTTP URL.
    // Use FeedBurner's working HTTPS endpoint directly so the downloader never
    // has to weaken its HTTPS-only redirect policy.
    url: "https://feeds.feedburner.com/GoogleOnlineSecurityBlog",
    feedHosts: ["feeds.feedburner.com"],
    itemHosts: ["security.googleblog.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 24 },
  },
  {
    id: "microsoft-security",
    publisher: "Microsoft Security Blog",
    publisherKey: "microsoft",
    primaryEntity: "Microsoft",
    relationship: "originating",
    format: "xml",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    feedHosts: ["www.microsoft.com"],
    itemHosts: ["www.microsoft.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 28 },
  },
  {
    id: "cert-cc-vulnerability-notes",
    publisher: "CERT/CC",
    publisherKey: "carnegie-mellon",
    primaryEntity: "CERT/CC",
    relationship: "originating",
    format: "xml",
    url: "https://kb.cert.org/vuls/atomfeed/",
    feedHosts: ["kb.cert.org"],
    itemHosts: ["kb.cert.org"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 30 },
  },
  {
    id: "cloudflare-blog",
    publisher: "Cloudflare",
    publisherKey: "cloudflare",
    primaryEntity: "Cloudflare",
    relationship: "originating",
    format: "xml",
    url: "https://blog.cloudflare.com/rss/",
    feedHosts: ["blog.cloudflare.com"],
    itemHosts: ["blog.cloudflare.com"],
    coverageDesks: ["security-and-privacy", "platforms-and-power"],
    deskPriors: { "platforms-and-power": 19, "security-and-privacy": 9 },
  },
  {
    id: "aws-whats-new",
    publisher: "AWS",
    publisherKey: "amazon",
    primaryEntity: "Amazon",
    relationship: "originating",
    format: "xml",
    url: "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
    feedHosts: ["aws.amazon.com"],
    itemHosts: ["aws.amazon.com"],
    itemPathPolicy: "append-trailing-slash",
    coverageDesks: ["platforms-and-power"],
    deskPriors: { "platforms-and-power": 22, "work-and-tools": 5 },
  },
  {
    id: "doj-antitrust",
    publisher: "U.S. Department of Justice Antitrust Division",
    publisherKey: "doj",
    primaryEntity: "U.S. Department of Justice",
    relationship: "originating",
    format: "xml",
    url: "https://www.justice.gov/news/rss?field_component=376&require_all=0&search_api_language=en&show_public_archived=0&type%5B0%5D=image_gallery&type%5B1%5D=press_release&type%5B2%5D=speech&type%5B3%5D=youtube_video",
    feedHosts: ["www.justice.gov"],
    itemHosts: ["www.justice.gov"],
    coverageDesks: ["platforms-and-power"],
    deskPriors: { "platforms-and-power": 27 },
  },
  {
    id: "federal-register-ftc",
    publisher: "Federal Register — Federal Trade Commission",
    publisherKey: "federal-register",
    primaryEntity: "FTC",
    relationship: "originating",
    format: "xml",
    url: "https://www.federalregister.gov/api/v1/documents.rss?conditions%5Bagencies%5D%5B%5D=federal-trade-commission",
    feedHosts: ["www.federalregister.gov"],
    itemHosts: ["www.federalregister.gov"],
    coverageDesks: ["platforms-and-power"],
    deskPriors: { "platforms-and-power": 26 },
  },
  {
    id: "google-deepmind",
    publisher: "Google DeepMind",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://deepmind.google/blog/rss.xml",
    feedHosts: ["deepmind.google"],
    itemHosts: ["deepmind.google"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 26 },
  },
  {
    id: "ai2-research",
    publisher: "Ai2",
    publisherKey: "allen-institute-for-ai",
    primaryEntity: "Ai2",
    relationship: "originating",
    format: "xml",
    url: "https://allenai.org/rss.xml",
    feedHosts: ["allenai.org"],
    itemHosts: ["allenai.org"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 24 },
  },
  {
    id: "mit-news-ai",
    publisher: "MIT News — Artificial Intelligence",
    publisherKey: "mit",
    primaryEntity: "MIT",
    relationship: "originating",
    format: "xml",
    url: "https://news.mit.edu/rss/topic/artificial-intelligence2",
    feedHosts: ["news.mit.edu"],
    itemHosts: ["news.mit.edu"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 17 },
  },
  {
    id: "berkeley-ai-research",
    publisher: "Berkeley Artificial Intelligence Research",
    publisherKey: "uc-berkeley",
    primaryEntity: "UC Berkeley",
    relationship: "originating",
    format: "xml",
    url: "https://bair.berkeley.edu/blog/feed.xml",
    feedHosts: ["bair.berkeley.edu"],
    itemHosts: ["bair.berkeley.edu"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 20 },
  },
  {
    id: "meta-engineering-ai",
    publisher: "Meta Engineering",
    publisherKey: "meta",
    primaryEntity: "Meta",
    relationship: "originating",
    format: "xml",
    url: "https://engineering.fb.com/category/ai-research/feed/",
    feedHosts: ["engineering.fb.com"],
    itemHosts: ["engineering.fb.com"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 18, "platforms-and-power": 5 },
  },
  {
    id: "amazon-science",
    publisher: "Amazon Science",
    publisherKey: "amazon",
    primaryEntity: "Amazon",
    relationship: "originating",
    format: "xml",
    url: "https://www.amazon.science/index.rss",
    feedHosts: ["www.amazon.science"],
    itemHosts: ["www.amazon.science"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 17, "platforms-and-power": 3 },
  },
  {
    id: "jetbrains-blog",
    publisher: "JetBrains",
    publisherKey: "jetbrains",
    primaryEntity: "JetBrains",
    relationship: "originating",
    format: "xml",
    url: "https://blog.jetbrains.com/feed/",
    feedHosts: ["blog.jetbrains.com"],
    itemHosts: ["blog.jetbrains.com"],
    coverageDesks: ["ai", "work-and-tools"],
    deskPriors: { ai: 6, "work-and-tools": 19 },
  },
  {
    id: "github-engineering",
    publisher: "GitHub Engineering",
    publisherKey: "microsoft",
    primaryEntity: "GitHub",
    relationship: "originating",
    format: "xml",
    url: "https://github.blog/engineering/feed/",
    feedHosts: ["github.blog"],
    itemHosts: ["github.blog"],
    coverageDesks: ["work-and-tools"],
    deskPriors: { ai: 3, "work-and-tools": 18, "security-and-privacy": 3 },
  },
  {
    id: "slack-engineering",
    publisher: "Slack Engineering",
    publisherKey: "salesforce",
    primaryEntity: "Slack",
    relationship: "originating",
    format: "xml",
    url: "https://slack.engineering/feed/",
    feedHosts: ["slack.engineering"],
    itemHosts: ["slack.engineering"],
    coverageDesks: ["work-and-tools"],
    deskPriors: {
      ai: 3,
      "work-and-tools": 14,
      "security-and-privacy": 3,
      "platforms-and-power": 3,
    },
  },
  {
    id: "chrome-developers",
    publisher: "Chrome for Developers",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://developer.chrome.com/static/blog/feed.xml",
    feedHosts: ["developer.chrome.com"],
    itemHosts: ["developer.chrome.com"],
    coverageDesks: ["work-and-tools"],
    deskPriors: {
      "work-and-tools": 18,
      "security-and-privacy": 3,
      "platforms-and-power": 3,
    },
  },
  {
    id: "nodejs-blog",
    publisher: "Node.js",
    publisherKey: "openjs-foundation",
    primaryEntity: "Node.js",
    relationship: "originating",
    format: "xml",
    url: "https://nodejs.org/en/feed/blog.xml",
    feedHosts: ["nodejs.org"],
    itemHosts: ["nodejs.org"],
    coverageDesks: ["work-and-tools", "security-and-privacy"],
    deskPriors: { "work-and-tools": 18, "security-and-privacy": 5 },
  },
  {
    id: "postman-blog",
    publisher: "Postman",
    publisherKey: "postman",
    primaryEntity: "Postman",
    relationship: "originating",
    format: "xml",
    url: "https://blog.postman.com/feed/",
    feedHosts: ["blog.postman.com"],
    itemHosts: ["blog.postman.com"],
    coverageDesks: ["ai", "work-and-tools"],
    deskPriors: { ai: 4, "work-and-tools": 16, "security-and-privacy": 3 },
  },
  {
    id: "rust-blog",
    publisher: "Rust Blog",
    publisherKey: "rust-foundation",
    primaryEntity: "Rust",
    relationship: "originating",
    format: "xml",
    url: "https://blog.rust-lang.org/feed.xml",
    feedHosts: ["blog.rust-lang.org"],
    itemHosts: ["blog.rust-lang.org"],
    coverageDesks: ["work-and-tools", "security-and-privacy"],
    deskPriors: { "work-and-tools": 18, "security-and-privacy": 4 },
  },
  {
    id: "netlify-changelog",
    publisher: "Netlify",
    publisherKey: "netlify",
    primaryEntity: "Netlify",
    relationship: "originating",
    format: "xml",
    url: "https://www.netlify.com/changelog/feed.xml",
    feedHosts: ["www.netlify.com"],
    itemHosts: [
      "www.netlify.com",
      "developers.netlify.com",
      "docs.netlify.com",
      "answers.netlify.com",
    ],
    coverageDesks: ["ai", "work-and-tools", "platforms-and-power"],
    deskPriors: {
      ai: 4,
      "work-and-tools": 18,
      "security-and-privacy": 3,
      "platforms-and-power": 6,
    },
  },
  {
    id: "ars-technica",
    publisher: "Ars Technica",
    publisherKey: "advance-publications",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    feedHosts: ["feeds.arstechnica.com"],
    itemHosts: ["arstechnica.com", "www.arstechnica.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 5, "work-and-tools": 6, "security-and-privacy": 7, "platforms-and-power": 7 },
  },
  {
    id: "the-verge",
    publisher: "The Verge",
    publisherKey: "penske-media",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.theverge.com/rss/index.xml",
    feedHosts: ["www.theverge.com"],
    itemHosts: ["www.theverge.com", "theverge.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 6, "work-and-tools": 7, "security-and-privacy": 4, "platforms-and-power": 7 },
  },
  {
    id: "techcrunch",
    publisher: "TechCrunch",
    publisherKey: "regent",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://techcrunch.com/feed/",
    feedHosts: ["techcrunch.com"],
    itemHosts: ["techcrunch.com", "www.techcrunch.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 7, "work-and-tools": 6, "security-and-privacy": 4, "platforms-and-power": 6 },
  },
  {
    id: "bleepingcomputer",
    publisher: "BleepingComputer",
    publisherKey: "bleeping-computer",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.bleepingcomputer.com/feed/",
    feedHosts: ["www.bleepingcomputer.com"],
    itemHosts: ["www.bleepingcomputer.com", "bleepingcomputer.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 24 },
  },
  {
    id: "wired",
    publisher: "WIRED",
    publisherKey: "advance-publications",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.wired.com/feed/rss",
    feedHosts: ["www.wired.com"],
    itemHosts: ["www.wired.com", "wired.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 6, "work-and-tools": 5, "security-and-privacy": 6, "platforms-and-power": 7 },
  },
  {
    id: "the-register",
    publisher: "The Register",
    publisherKey: "situation-publishing",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.theregister.com/?lab_viewport=rss",
    feedHosts: ["www.theregister.com"],
    itemHosts: ["www.theregister.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 7, "work-and-tools": 8, "security-and-privacy": 9, "platforms-and-power": 8 },
  },
  {
    id: "guardian-technology",
    publisher: "The Guardian",
    publisherKey: "guardian-media-group",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.theguardian.com/us/technology/rss",
    feedHosts: ["www.theguardian.com"],
    itemHosts: ["www.theguardian.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 6, "work-and-tools": 5, "security-and-privacy": 6, "platforms-and-power": 9 },
  },
  {
    id: "bbc-technology",
    publisher: "BBC News",
    publisherKey: "bbc",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
    feedHosts: ["feeds.bbci.co.uk"],
    itemHosts: ["www.bbc.com", "www.bbc.co.uk"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 6, "work-and-tools": 5, "security-and-privacy": 5, "platforms-and-power": 7 },
  },
  {
    id: "npr-technology",
    publisher: "NPR",
    publisherKey: "npr",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://feeds.npr.org/1019/rss.xml",
    feedHosts: ["feeds.npr.org"],
    itemHosts: ["www.npr.org", "npr.org"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 5, "work-and-tools": 4, "security-and-privacy": 5, "platforms-and-power": 7 },
  },
  {
    id: "securityweek",
    publisher: "SecurityWeek",
    publisherKey: "wired-business-media",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.securityweek.com/feed/",
    feedHosts: ["www.securityweek.com"],
    itemHosts: ["www.securityweek.com", "securityweek.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 24 },
  },
  {
    id: "dark-reading",
    publisher: "Dark Reading",
    publisherKey: "informa-techtarget",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.darkreading.com/rss.xml",
    feedHosts: ["www.darkreading.com"],
    itemHosts: ["www.darkreading.com", "darkreading.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 23 },
  },
  {
    id: "mit-technology-review-ai",
    publisher: "MIT Technology Review",
    publisherKey: "mit",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
    feedHosts: ["www.technologyreview.com"],
    itemHosts: ["www.technologyreview.com"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 8, "work-and-tools": 3, "platforms-and-power": 3 },
  },
  {
    id: "ieee-spectrum-ai",
    publisher: "IEEE Spectrum",
    publisherKey: "ieee",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
    feedHosts: ["spectrum.ieee.org"],
    itemHosts: ["spectrum.ieee.org"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 9, "work-and-tools": 4, "platforms-and-power": 3 },
  },
]);
