/**
 * A deliberately small, first-party-heavy source list for the free pilot.
 *
 * Feed and article hosts are exact allowlists. A source may redirect only to a
 * host named here; adding a source is therefore a reviewed code change rather
 * than something source-controlled XML can do at runtime.
 */
export const FREE_FEED_SOURCES = Object.freeze([
  {
    id: "openai-news",
    publisher: "OpenAI",
    publisherKey: "openai",
    primaryEntity: "OpenAI",
    relationship: "originating",
    format: "xml",
    url: "https://openai.com/news/rss.xml",
    feedHosts: ["openai.com", "www.openai.com"],
    itemHosts: ["openai.com", "www.openai.com"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 28, "work-and-tools": 5 },
  },
  {
    id: "google-ai",
    publisher: "Google",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://blog.google/technology/ai/rss/",
    feedHosts: ["blog.google"],
    itemHosts: ["blog.google"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 26, "work-and-tools": 4, "platforms-and-power": 3 },
  },
  {
    id: "google-research",
    publisher: "Google Research",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    url: "https://research.google/blog/rss/",
    feedHosts: ["research.google"],
    itemHosts: ["research.google"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 22 },
  },
  {
    id: "microsoft-research",
    publisher: "Microsoft Research",
    publisherKey: "microsoft",
    primaryEntity: "Microsoft",
    relationship: "originating",
    format: "xml",
    url: "https://www.microsoft.com/en-us/research/feed/",
    feedHosts: ["www.microsoft.com"],
    itemHosts: ["www.microsoft.com"],
    coverageDesks: ["ai", "work-and-tools"],
    deskPriors: { ai: 16, "work-and-tools": 8 },
  },
  {
    id: "hugging-face-blog",
    publisher: "Hugging Face",
    publisherKey: "hugging-face",
    primaryEntity: "Hugging Face",
    relationship: "originating",
    format: "xml",
    url: "https://huggingface.co/blog/feed.xml",
    feedHosts: ["huggingface.co"],
    itemHosts: ["huggingface.co"],
    coverageDesks: ["ai"],
    deskPriors: { ai: 25, "work-and-tools": 3 },
  },
  {
    id: "github-changelog",
    publisher: "GitHub",
    publisherKey: "microsoft",
    primaryEntity: "GitHub",
    relationship: "originating",
    format: "xml",
    url: "https://github.blog/changelog/feed/",
    feedHosts: ["github.blog"],
    itemHosts: ["github.blog"],
    coverageDesks: ["work-and-tools"],
    deskPriors: { "work-and-tools": 24, "security-and-privacy": 4 },
  },
  {
    id: "mozilla-hacks",
    publisher: "Mozilla Hacks",
    publisherKey: "mozilla",
    primaryEntity: "Mozilla",
    relationship: "originating",
    format: "xml",
    url: "https://hacks.mozilla.org/feed/",
    feedHosts: ["hacks.mozilla.org"],
    itemHosts: ["hacks.mozilla.org"],
    coverageDesks: ["work-and-tools"],
    deskPriors: { "work-and-tools": 15, "security-and-privacy": 5 },
  },
  {
    id: "cisa-advisories",
    publisher: "CISA",
    publisherKey: "cisa",
    primaryEntity: "CISA",
    relationship: "originating",
    format: "xml",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    feedHosts: ["www.cisa.gov"],
    itemHosts: ["www.cisa.gov"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 30 },
  },
  {
    id: "google-security",
    publisher: "Google Security Blog",
    publisherKey: "google",
    primaryEntity: "Google",
    relationship: "originating",
    format: "xml",
    // The vanity Blogger endpoint currently redirects through an HTTP URL.
    // Use FeedBurner's working HTTPS endpoint directly so the downloader never
    // has to weaken its HTTPS-only redirect policy.
    url: "https://feeds.feedburner.com/GoogleOnlineSecurityBlog",
    feedHosts: ["feeds.feedburner.com"],
    itemHosts: ["security.googleblog.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 24 },
  },
  {
    id: "cloudflare-blog",
    publisher: "Cloudflare",
    publisherKey: "cloudflare",
    primaryEntity: "Cloudflare",
    relationship: "originating",
    format: "xml",
    url: "https://blog.cloudflare.com/rss/",
    feedHosts: ["blog.cloudflare.com"],
    itemHosts: ["blog.cloudflare.com"],
    coverageDesks: ["security-and-privacy", "platforms-and-power"],
    deskPriors: { "platforms-and-power": 19, "security-and-privacy": 9 },
  },
  {
    id: "aws-whats-new",
    publisher: "AWS",
    publisherKey: "amazon",
    primaryEntity: "Amazon",
    relationship: "originating",
    format: "xml",
    url: "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
    feedHosts: ["aws.amazon.com"],
    itemHosts: ["aws.amazon.com"],
    coverageDesks: ["platforms-and-power"],
    deskPriors: { "platforms-and-power": 22, "work-and-tools": 5 },
  },
  {
    id: "ftc-competition",
    publisher: "U.S. Federal Trade Commission",
    publisherKey: "ftc",
    primaryEntity: "FTC",
    relationship: "originating",
    format: "xml",
    url: "https://www.ftc.gov/feeds/press-release-competition.xml",
    feedHosts: ["www.ftc.gov"],
    itemHosts: ["www.ftc.gov"],
    coverageDesks: ["platforms-and-power"],
    deskPriors: { "platforms-and-power": 28 },
  },
  {
    id: "ars-technica",
    publisher: "Ars Technica",
    publisherKey: "advance-publications",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    feedHosts: ["feeds.arstechnica.com"],
    itemHosts: ["arstechnica.com", "www.arstechnica.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 5, "work-and-tools": 6, "security-and-privacy": 7, "platforms-and-power": 7 },
  },
  {
    id: "the-verge",
    publisher: "The Verge",
    publisherKey: "penske-media",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.theverge.com/rss/index.xml",
    feedHosts: ["www.theverge.com"],
    itemHosts: ["www.theverge.com", "theverge.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 6, "work-and-tools": 7, "security-and-privacy": 4, "platforms-and-power": 7 },
  },
  {
    id: "techcrunch",
    publisher: "TechCrunch",
    publisherKey: "regent",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://techcrunch.com/feed/",
    feedHosts: ["techcrunch.com"],
    itemHosts: ["techcrunch.com", "www.techcrunch.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 7, "work-and-tools": 6, "security-and-privacy": 4, "platforms-and-power": 6 },
  },
  {
    id: "bleepingcomputer",
    publisher: "BleepingComputer",
    publisherKey: "bleeping-computer",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.bleepingcomputer.com/feed/",
    feedHosts: ["www.bleepingcomputer.com"],
    itemHosts: ["www.bleepingcomputer.com", "bleepingcomputer.com"],
    coverageDesks: ["security-and-privacy"],
    deskPriors: { "security-and-privacy": 24 },
  },
  {
    id: "wired",
    publisher: "WIRED",
    publisherKey: "advance-publications",
    primaryEntity: null,
    relationship: "independent",
    format: "xml",
    url: "https://www.wired.com/feed/rss",
    feedHosts: ["www.wired.com"],
    itemHosts: ["www.wired.com", "wired.com"],
    coverageDesks: ["ai", "work-and-tools", "security-and-privacy", "platforms-and-power"],
    deskPriors: { ai: 6, "work-and-tools": 5, "security-and-privacy": 6, "platforms-and-power": 7 },
  },
]);
